version: '3'

services:
  cassandra-seed:
    container_name: cassandra-seed
    image: cassandra
    ports:
      - "9042:9042"   # Native protocol clients
      # - "7199:7199"   # JMX
      # - "9160:9160"   # Thrift clients
    volumes:
      - ./local_cassandra_data_seed:/var/lib/cassandra

  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=student # as in l1-demo-1-creating-a-table-with-postgres.ipynb
      - POSTGRES_PASSWORD=student
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./local_pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always