version: '3'

services:
  cassandra:
    image: 'cassandra'
    ports:
      - '9040:9042'

  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always